server:
  port: 8080

spring:

  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/static,classpath:/resources/,file:${web.upload-path}
  mvc:
    static-path-pattern: /image/**
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/classroom?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: 123456

mybatis:
  mapper-locations:
    - classpath*:dao/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  configuration:
#  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
app:
  uploadFolder: D://uploadFiles/
  previewPath: http://127.0.0.1:8080/image/
web:
  upload-path: D://uploadFiles/
#logging:
#  config:classpath:logback.xml

